source "https://rubygems.org"

ruby "3.4.6"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.5"
gem "puma", "~> 6.4"
gem "rack-cors"
gem "bcrypt", "~> 3.1"
gem "jwt"
gem "bootsnap", require: false

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "dotenv-rails"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "debug"
end

group :development do
  gem "listen", "~> 3.8"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.1"
end
