services:
  - type: web
    name: pwa-ecommerce-backend
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        sync: false
