# frozen_string_literal: true

# This file is auto-generated by Active Record's schema dumper. Instead of editing this file, please use the
# migrations feature of Active Record to incrementally modify your database, and then regenerate this schema
# definition.

ActiveRecord::Schema[7.1].define(version: 0) do
end
